name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v4

    - name: Composer install
      run: composer install

    - name: Run cscheck
      run: composer cscheck

    - name: Run phpstan
      run: composer phpstan

    - name: Run phpunit
      run: php vendor/bin/phpunit --testdox tests
